#specifing the path of the csv file

path <- file.path("~","sbe304-fall19-project-sbe304-2021-team09","heart-disease","processed.cleveland.data")
#path <- file.path("~","Desktop","SBE304-ML","sbe304-fall19-project-sbe304-2021-team09","heart-disease","processed.cleveland.data")
path


### NOTE : if this path generated an error,simply edit it to match yours on your machine,
###       could look like this "/home/adel/sbe304-fall19-project-sbe304-2021-team09/echocardiogram-uci/echocardiogram.csv"

#retrieving dataset from csv file
data <- read.csv(path,stringsAsFactors = FALSE)

#sampling the data
head(data)
str(data)
#data names vector 
headerNames <- c("age","sex","cp","trestbps","chol","fbs","restecg"
                 ,"thalach","exang","oldpeak","slope","ca","thal","Class")
#renaming the dataframe columns
colnames(data) <- headerNames

#sampling filtered dataset and getting info
head(data)
str(data)
data
summary(data)
#counting missing values
sum(is.na(data)) # No missing found

#summary of data
summary(data)
#counting missing values 
sapply(data , function(x) sum(is.na(data))) # No missing found

#adding new col to data and removing class
names(data)
target <- data$Class

makeBinary <- function(x){
  if(x == 0){
    return ("Negative")
    }
    
  else{
    return ("Postive")
  }
}
##"factoring" won't work with binary nums.
##So , we used "Postive" , "Negative"
target<-sapply(target,makeBinary)
target
data<-cbind(data,target)
str(data)
keep <- c(names(data)[1:13],names(data[15]))
keep
data <- data[keep]
head(data)
#check data types
str(data)

#Categorical feature encoding
library(dplyr) 
data <- data %>%
    mutate(
        ca = as.numeric(ca),
        thal = as.numeric(thal),
        target = as.factor(target)
    )

#removing NAs generated by mutate
data <- na.omit(data) 

#check data types
str(data)

data
# No missing found

sapply(data , function(x) sum(is.na(data))) 

library(caret)

cntrl <- trainControl(
    method ="repeatedcv",
    repeats = 5,
    classProbs = TRUE ,
    summaryFunction = twoClassSummary
)

##Naive Bayes
set.seed(420)

NB_Fit<- train(
    target ~.,
    data = data,
    method = "naive_bayes",
    preProc = c("center","scale"),
    tuneGrid = expand.grid(.laplace = 0, .usekernel = TRUE, .adjust = 1),
    trControl = cntrl,
    metric = "ROC"
)

NB_Fit

##Desicision Tree
DT_Fit<- train(
    target ~.,
    data = data,
    method = "rpart",
    preProc = c("center","scale"),
    tuneLength =15,
    trControl = cntrl,
    metric = "ROC"
)

DT_Fit

##Logistic Reg. Training
Log_Fit<- train(
    target ~.,
    data = data,
    method = "glm",
    preProc = c("center","scale"),
    tuneLength =15,
    trControl = cntrl,
    metric = "ROC"
)
Log_Fit

